const museumImages = {
  'allard-pierson-amsterdam': '/images/allard-pierson-amsterdam.jpg',
  'amsterdam-museum-amsterdam': '/images/amsterdam-museum-amsterdam.webp',
  'amsterdam-tulip-museum-amsterdam': '/images/amsterdam-tulip-museum-amsterdam.jpg',
  'anne-frank-huis-amsterdam': '/images/anne-frank-huis-amsterdam.jpg',
  'body-worlds-amsterdam': '/images/body-worlds-amsterdam.jpg',
  'eye-filmmuseum-amsterdam': '/images/eye-filmmuseum-amsterdam.jpg',
  'foam-fotografiemuseum-amsterdam': '/images/foam-fotografiemuseum-amsterdam.webp',
  'hart-museum-amsterdam': '/images/hart-museum-amsterdam.jpg',
  'het-grachtenmuseum-amsterdam': '/images/het-grachtenmuseum-amsterdam.jpg',
  'het-schip-amsterdam': '/images/het-schip-amsterdam.jpg',
  'joods-museum-amsterdam': '/images/joods-museum-amsterdam.jpeg',
  'kattenkabinet-amsterdam': '/images/kattenkabinet-amsterdam.jpg',
  'micropia-museum-amsterdam': '/images/micropia-museum-amsterdam.jpg',
  'moco-museum-amsterdam': '/images/moco-museum-amsterdam.webp',
  'museum-van-loon-amsterdam': '/images/museum-van-loon-amsterdam.jpg',
  'nemo-science-museum-amsterdam': '/images/nemo-science-museum-amsterdam.jpg',
  'nxt-museum-amsterdam': '/images/nxt-museum-amsterdam.webp',
  'ons-lieve-heer-op-solder-amsterdam': '/images/ons-lieve-heer-op-solder-amsterdam.jpg',
  'rembrandthuis-amsterdam': '/images/rembrandthuis-amsterdam.jpg',
  'rijksmuseum-amsterdam': '/images/rijksmuseum-amsterdam.png',
  'scheepvaartmuseum-amsterdam': '/images/scheepvaartmuseum-amsterdam.jpg',
  'stedelijk-museum-amsterdam': '/images/stedelijk-museum-amsterdam.jpg',
  'straat-museum-amsterdam': '/images/straat-museum-amsterdam.jpg',
  'tropenmuseum-amsterdam': '/images/wereldmuseum-amsterdam.jpg',
  'van-gogh-museum-amsterdam': '/images/van-gogh-museum-amsterdam.jpg',
  'wereldmuseum-amsterdam': '/images/wereldmuseum-amsterdam.jpg',
  'woonbootmuseum-amsterdam': '/images/woonbootmuseum-amsterdam.jpg',
};

export default museumImages;
