const museumSummaries = {
  'allard-pierson-amsterdam': 'Archaeological and cultural history from ancient civilizations.',
  'amsterdam-museum-amsterdam': 'Stories of Amsterdam\'s past, present and future.',
  'amsterdam-tulip-museum-amsterdam': 'History of the Dutch tulip and bulb trade.',
  'anne-frank-huis-amsterdam': 'Secret annex where Anne Frank wrote her diary.',
  'body-worlds-amsterdam': 'Interactive exhibits about the human body.',
  'eye-filmmuseum-amsterdam': 'Dutch film heritage and cinema culture.',
  'foam-fotografiemuseum-amsterdam': 'Contemporary photography exhibitions.',
  'hart-museum-amsterdam': 'Art and stories about the human heart.',
  'het-grachtenmuseum-amsterdam': 'Canal house museum explaining Amsterdam\'s waterways.',
  'het-schip-amsterdam': 'Amsterdam School architecture in workers housing.',
  'huis-marseille-amsterdam': 'Photography in a historic canal house.',
  'joods-museum-amsterdam': 'Jewish history and culture in the Netherlands.',
  'kattenkabinet-amsterdam': 'Art dedicated to cats and cat lovers.',
  'micropia-museum-amsterdam': 'World of microbes and invisible life.',
  'moco-museum-amsterdam': 'Modern and contemporary art in a townhouse.',
  'museum-van-loon-amsterdam': '18th-century canal house and family life.',
  'nemo-science-museum-amsterdam': 'Hands-on science and technology exhibits.',
  'nxt-museum-amsterdam': 'Immersive digital art installations.',
  'ons-lieve-heer-op-solder-amsterdam': 'Secret attic church from the 17th century.',
  'rembrandthuis-amsterdam': 'Home and studio of painter Rembrandt.',
  'rijksmuseum-amsterdam': 'Dutch art and history with masterpieces.',
  'scheepvaartmuseum-amsterdam': 'Maritime history and seafaring.',
  'stedelijk-museum-amsterdam': 'Modern and contemporary art collections.',
  'straat-museum-amsterdam': 'Street art and graffiti in a huge warehouse.',
  'tropenmuseum-amsterdam': 'World cultures and ethnographic collections.',
  'van-gogh-museum-amsterdam': 'Van Gogh\'s paintings and letters.',
  'wereldmuseum-amsterdam': 'World cultures and ethnography in Amsterdam.',
  'woonbootmuseum-amsterdam': 'Life on Amsterdam\'s houseboats.',
};

export default museumSummaries;
