const museumTicketUrls = {
  'allard-pierson-amsterdam':
    'https://www.getyourguide.com/amsterdam-l36/amsterdam-allard-pierson-museum-entry-ticket-t419487/?partner_id=I8RVSW6&utm_medium=local_partners',
  'amsterdam-museum-amsterdam':
    'https://www.getyourguide.com/amsterdam-l36/amsterdam-amsterdam-museum-entry-ticket-t417547/?partner_id=I8RVSW6&utm_medium=local_partners',
  'anne-frank-huis-amsterdam':
    'https://tickets.annefrank.org/en-US/tickets',
  'body-worlds-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-body-worlds-the-happiness-project-skip-the-line-ticket-p972859/booking_details/?partner=museaumbuddy-179611',
  'eye-filmmuseum-amsterdam':
    'https://www.eyefilm.nl/en/whats-on',
  'foam-fotografiemuseum-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-foam-photography-museum-entry-ticket-p972892/booking_details/?partner=museaumbuddy-179611',
  'hart-museum-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-h-art-museum-amsterdam-p1093179/booking_details/?partner=museaumbuddy-179611',
  'het-grachtenmuseum-amsterdam':
    'https://tickets.grachten.museum/en/tickets',
  'het-schip-amsterdam':
    'https://www.getyourguide.com/museum-het-schip-l2984/amsterdam-guided-tour-of-the-het-ship-museum-exhibition-t413595/?partner_id=I8RVSW6&utm_medium=local_partners',
  'huis-marseille-amsterdam':
    'https://tickets.huismarseille.nl/en/tickets',
  'joods-museum-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-jewish-museum-p974556/booking_details/?partner=museaumbuddy-179611',
  'kattenkabinet-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-the-cat-cabinet-entry-ticket-p974612/booking_details/?partner=museaumbuddy-179611',
  'micropia-museum-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-artis-micropia-entry-ticket-p973953/booking_details/?partner=museaumbuddy-179611',
  'moco-museum-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-moco-museum-amsterdam-entry-ticket-p974431/booking_details/?partner=museaumbuddy-179611',
  'museum-van-loon-amsterdam':
    'https://www.getyourguide.com/amsterdam-l36/amsterdam-museum-van-loon-entry-ticket-t632666/?partner_id=I8RVSW6&utm_medium=local_partners',
  'nemo-science-museum-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-nemo-science-museum-entry-ticket-p706076/booking_details/?partner=museaumbuddy-179611',
  'nxt-museum-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-nxt-museum-entry-ticket-p1062808/booking_details/?partner=museaumbuddy-179611',
  'ons-lieve-heer-op-solder-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-museum-our-lord-in-the-attic-entry-ticket-audio-guide-p974148/booking_details/?partner=museaumbuddy-179611',
  'rembrandthuis-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-rembrandt-house-museum-entry-ticket-multimedia-guide-p972886/booking_details/?partner=museaumbuddy-179611',
  'rijksmuseum-amsterdam':
    'https://www.getyourguide.com/amsterdam-l36/amsterdam-rijksmuseum-entry-ticket-t7135/?partner_id=I8RVSW6&utm_medium=local_partners',
  'scheepvaartmuseum-amsterdam':
    'https://www.getyourguide.com/het-scheepvaartmuseum-l2999/fast-line-tickets-the-national-maritime-museum-t46115/?partner_id=I8RVSW6&utm_medium=local_partners',
  'stedelijk-museum-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-stedelijk-museum-amsterdam-entry-ticket-p973982/booking_details/?partner=museaumbuddy-179611',
  'straat-museum-amsterdam':
    'https://www.getyourguide.com/straat-museum-l158877/amsterdam-streetart-museum-straat-ticket-t395197/?partner_id=I8RVSW6&utm_medium=local_partners',
  'van-gogh-museum-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-van-gogh-museum-entry-ticket-p974079/booking_details/?partner=museaumbuddy-179611',
  'wereldmuseum-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-wereldmuseum-amsterdam-entry-ticket-p973054/booking_details/?partner=museaumbuddy-179611',
  'woonbootmuseum-amsterdam':
    'https://www.tiqets.com/en/checkout/tickets-for-houseboat-museum-entry-ticket-audio-guide-p1103842/booking_details/?partner=museaumbuddy-179611',
};

export default museumTicketUrls;

