const museumCategories = {
  'allard-pierson-amsterdam': ['history', 'culture'],
  'amsterdam-museum-amsterdam': ['history', 'culture'],
  'anne-frank-huis-amsterdam': ['history'],
  'body-worlds-amsterdam': ['science'],
  'eye-filmmuseum-amsterdam': ['modernArt', 'culture'],
  'foam-fotografiemuseum-amsterdam': ['modernArt', 'culture'],
  'hart-museum-amsterdam': ['science', 'modernArt'],
  'het-grachtenmuseum-amsterdam': ['history'],
  'het-schip-amsterdam': ['history', 'culture'],
  'huis-marseille-amsterdam': ['modernArt', 'culture'],
  'joods-museum-amsterdam': ['history', 'culture'],
  'kattenkabinet-amsterdam': ['culture', 'kids'],
  'micropia-museum-amsterdam': ['science', 'kids'],
  'moco-museum-amsterdam': ['modernArt', 'culture'],
  'museum-van-loon-amsterdam': ['history', 'culture'],
  'nemo-science-museum-amsterdam': ['science', 'kids'],
  'nxt-museum-amsterdam': ['modernArt'],
  'ons-lieve-heer-op-solder-amsterdam': ['history'],
  'rembrandthuis-amsterdam': ['history', 'culture'],
  'rijksmuseum-amsterdam': ['history', 'modernArt'],
  'scheepvaartmuseum-amsterdam': ['history', 'kids'],
  'stedelijk-museum-amsterdam': ['modernArt'],
  'straat-museum-amsterdam': ['modernArt', 'culture'],
  'tropenmuseum-amsterdam': ['history', 'culture', 'kids'],
  'van-gogh-museum-amsterdam': ['modernArt'],
  'wereldmuseum-amsterdam': ['history', 'culture'],
  'woonbootmuseum-amsterdam': ['history', 'kids'],
};

export default museumCategories;
