const museumImageCredits = {
  'allard-pierson-amsterdam': {
    author: 'Hnapel',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    url: 'https://commons.wikimedia.org/wiki/File:Allard_Pierson_Museum_ambient_light_01.jpg',
  },
  'amsterdam-museum-amsterdam': {
    author: 'Rachel Ecclestone',
    license: 'CC BY-SA 4.0',
    source: 'Hart Amsterdam',
    url: 'https://hart.amsterdam/nl/collectie/object/amphoto/230676',
  },
  'anne-frank-huis-amsterdam': {
    author: 'Anne Frank House',
    license: '',
    source: 'Flickr',
    url: 'https://www.flickr.com/photos/collection_annefrankhouse/31957984331/in/album-72157678680505575',
  },
  'body-worlds-amsterdam': {
    author: 'Body Worlds',
    license: '',
    source: 'Flickr',
    url: 'https://www.flickr.com/photos/bodyworldsnl/40490526852/',
  },
  'eye-filmmuseum-amsterdam': {
    author: 'Corinne de Korver',
    license: '',
    source: 'Eye Filmmuseum',
    url: 'https://www.eyefilm.nl/en/about-eye/press/visual-material',
  },
  'foam-fotografiemuseum-amsterdam': {
    author: 'Dqfn13',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    url: 'https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en',
  },
  'hart-museum-amsterdam': {
    author: 'Eva Bloem',
    license: '',
    source: "H'Art Museum",
    url: 'https://www.hartmuseum.nl/pers/beeldmateriaal/',
  },
  'het-grachtenmuseum-amsterdam': {
    author: 'Evert100',
    license: 'Public domain',
    source: 'Wikimedia Commons',
    url: 'https://commons.wikimedia.org/wiki/File:Herengracht_386.jpg',
  },
  'huis-marseille-amsterdam': {
    author: 'Kaasverhuur',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    url: 'https://creativecommons.org/licenses/by-sa/4.0',
  },
  'joods-museum-amsterdam': {
    author: 'Anneke Hymmen',
    license: '',
    source: 'Joods Cultureel Kwartier',
    url: 'https://jck.nl/pers/beeldmateriaal/beeldmateriaal-joods-museum',
  },
  'kattenkabinet-amsterdam': {
    author: 'PersianDutchNetwork',
    license: 'Public domain',
    source: 'Wikimedia Commons',
    url: 'https://commons.wikimedia.org/wiki/File:Cat_Cabinet_face_Amsterdam-Photo_by_Pejman_Akbarzadeh_Persian_Dutch_Network.jpg',
  },
  'micropia-museum-amsterdam': {
    author: 'Yann Caradec',
    license: 'CC BY-SA 2.0',
    source: 'Wikimedia Commons',
    url: 'https://creativecommons.org/licenses/by-sa/2.0',
  },
  'moco-museum-amsterdam': {
    author: 'BGCopy',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    url: 'https://creativecommons.org/licenses/by-sa/4.0',
  },
  'het-schip-amsterdam': {
    author: 'Marcel Westhof',
    license: '',
    source: 'Museum Het Schip',
    url: 'https://www.hetschip.nl/over-het-museum/voor-de-pers/pers-het-schip',
  },
  'museum-van-loon-amsterdam': {
    author: 'Remi Mathis',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons',
    url: 'https://creativecommons.org/licenses/by-sa/3.0',
  },
  'nemo-science-museum-amsterdam': {
    author: 'DigiDaan',
    license: '',
    source: 'NEMO Science Museum',
    url: 'https://www.nemosciencemuseum.nl/en/press/photographs',
  },
  'nxt-museum-amsterdam': {
    author: 'Nxt Museum',
    license: '',
    source: 'Nxt Museum',
    url: 'https://nxtmuseum.com/',
  },
  'ons-lieve-heer-op-solder-amsterdam': {
    author: 'Rebekka Mell',
    license: '',
    source: 'Ons Lieve Heer op Solder',
    url: 'https://opsolder.nl/en/media-and-press/',
  },
  'rembrandthuis-amsterdam': {
    author: 'Aad Hoogendoorn',
    license: '',
    source: 'Museum Het Rembrandthuis',
    url: 'https://rembrandthuis.pr-newsroom.nl/brand-assets',
  },
  'rijksmuseum-amsterdam': {
    author: 'Rijksmuseum',
    license: 'Public domain',
    source: 'Rijksmuseum',
    url: 'https://creativecommons.org/publicdomain/mark/1.0/deed.nl',
  },
  'scheepvaartmuseum-amsterdam': {
    author: 'Het Scheepvaartmuseum',
    license: '',
    source: 'Het Scheepvaartmuseum',
    url: 'https://www.hetscheepvaartmuseum.nl/over-ons/pers/beeld-en-logos/voc-schip-amsterdam',
  },
  'stedelijk-museum-amsterdam': {
    author: 'John Lewis Marshall',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    url: 'https://creativecommons.org/licenses/by-sa/4.0',
  },
  'straat-museum-amsterdam': {
    author: 'Matthias Süßen',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    url: 'https://creativecommons.org/licenses/by-sa/4.0',
  },
  'wereldmuseum-amsterdam': {
    author: 'Jordi Huisman',
    license: '',
    source: 'Wereldmuseum Amsterdam',
    url: 'https://amsterdam.wereldmuseum.nl/nl/over-wereldmuseum-amsterdam/pers/persbeeld?_gl=1*133q1gh*_up*MQ..*_ga*MjE0NTU3NDE0MS4xNzU3NjY4MzI1*_ga_DGKD64GL6R*czE3NTc2NjgzMjQkbzEkZzEkdDE3NTc2NjgzMzQkajUwJGwwJGg0MTQwNjYwMjg.',
  },
  'tropenmuseum-amsterdam': {
    author: 'Jordi Huisman',
    license: '',
    source: 'Wereldmuseum Amsterdam',
    url: 'https://amsterdam.wereldmuseum.nl/nl/over-wereldmuseum-amsterdam/pers/persbeeld?_gl=1*133q1gh*_up*MQ..*_ga*MjE0NTU3NDE0MS4xNzU3NjY4MzI1*_ga_DGKD64GL6R*czE3NTc2NjgzMjQkbzEkZzEkdDE3NTc2NjgzMzQkajUwJGwwJGg0MTQwNjYwMjg.',
  },
  'van-gogh-museum-amsterdam': {
    author: 'Van Gogh Museum',
    license: '',
    source: 'Van Gogh Museum',
    url: 'https://www.vangoghmuseum.nl/nl/collectie/s0016V1962#details',
  },
  'woonbootmuseum-amsterdam': {
    author: 'Stefan Flöper',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons',
    url: 'https://creativecommons.org/licenses/by-sa/4.0',
  },
};

export default museumImageCredits;
