const museumImages = {
  'allard-pierson-amsterdam': '/images/Eric de Redelijkheid Allard Pierson Museum.jpg',
  'amsterdam-museum-amsterdam':
    '/images/Amsterdam Museum Rachel Ecclestone_CC_BY_SA 4_0_via Hart Amsterdam.jpg',
  'anne-frank-huis-amsterdam': '/images/Anne Frank.jpg',
  'body-worlds-amsterdam': '/images/Body Worlds Franz Kohler.jpg',
  'eye-filmmuseum-amsterdam': '/images/Eye Sam Amil.jpg',
  'foam-fotografiemuseum-amsterdam': '/images/FOAM Jan-WIllem Doornenbal.jpg',
  'hart-museum-amsterdam': "/images/H'art_Monique Vermeulen.jpg",
  'het-grachtenmuseum-amsterdam': '/images/Het grachtenmuseum Thomas Quine.jpg',
  'het-schip-amsterdam': '/images/Het Schip_Marcel Westhoff_MWFF4975 1.jpg',
  'huis-marseille-amsterdam': '/images/Huis Marseille_Hans Luthart.jpg',
  'joods-museum-amsterdam': '/images/Joods Historisch Museum_Michele Ahin.jpg',
  'kattenkabinet-amsterdam': '/images/KattenKabinet_Taylor Dahlin.jpg',
  'micropia-museum-amsterdam': null,
  'moco-museum-amsterdam': null,
  'museum-van-loon-amsterdam': '/images/Van Loon_ Willem van Valkenburg.jpg',
  'nemo-science-museum-amsterdam': '/images/NEMO_Randy Connolly.jpg',
  'nxt-museum-amsterdam': '/images/Nxt Museum_Rob Oo.jpg',
  'ons-lieve-heer-op-solder-amsterdam': '/images/Ons Lieve heer op Solder_Gary Campell Hall.jpg',
  'rembrandthuis-amsterdam': '/images/Rembrandt Huis_Thomas Quine.jpg',
  'rijksmuseum-amsterdam': '/images/Nachtwacht via Rijksmuseum.jpg',
  'scheepvaartmuseum-amsterdam': '/images/Het scheepsvaartmudeum_Rob Oo.jpg',
  'stedelijk-museum-amsterdam': '/images/liam-mcgarry-stedelijk.jpg',
  'straat-museum-amsterdam': '/images/STRAAT_Frank Kovalchek.jpg',
  'tropenmuseum-amsterdam': '/images/Wereldmuseum_Alexander Svensson.jpg',
  'van-gogh-museum-amsterdam': '/images/Van Gogh via Rijksmuseum.jpg',
  'wereldmuseum-amsterdam': '/images/Wereldmuseum_Alexander Svensson.jpg',
  'woonbootmuseum-amsterdam': '/images/Woonbootmuseum_Stefan.jpg',
};

export default museumImages;
