import './globals.css'
import { Quicksand } from 'next/font/google'
import type { Metadata } from 'next'

const quicksand = Quicksand({ subsets: ['latin'], variable: '--font-quicksand', weight: ['400','500','700'], display: 'swap' })

export const metadata: Metadata = {
  title: 'Museum Buddy App',
  description: 'Generated by create-next-app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={quicksand.variable}>{children}</body>
    </html>
  )
}
